//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDemo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesBillDetails
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> salesBillId { get; set; }
        public Nullable<int> quantity { get; set; }
        public decimal price { get; set; }
        public decimal totalPrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual salesBill salesBill { get; set; }
    }
}
