//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDemo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesView
    {
        public string Name { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<int> quantity { get; set; }
        public decimal totalPrice { get; set; }
        public string catName { get; set; }
        public string cusName { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
