//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDemo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesBill
    {
        public salesBill()
        {
            this.salesBillDetails = new HashSet<salesBillDetails>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> totalAfterDiscount { get; set; }
        public string notes { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<salesBillDetails> salesBillDetails { get; set; }
    }
}
