//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDemo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.salesBill = new HashSet<salesBill>();
        }
    
        public int id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
        public Nullable<bool> control_users { get; set; }
        public Nullable<bool> add_product { get; set; }
        public Nullable<bool> add_supplier { get; set; }
        public Nullable<bool> add_customer { get; set; }
        public Nullable<bool> add_invoice { get; set; }
        public Nullable<bool> add_report { get; set; }
        public Nullable<bool> edit_price { get; set; }
        public Nullable<bool> show_product { get; set; }
    
        public virtual ICollection<salesBill> salesBill { get; set; }
    }
}
